name: 'Triage: Close issues with no response'

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  workflow_call:
    inputs:
      days_until_close:
        description: 'Number of days until issue is closed'
        type: number
        required: false
        default: 14
      response_required_label:
        description: 'Label that indicates a response is required'
        type: string
        required: false
        default: 'more-info-needed'
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

permissions:
  issues: write

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          closeComment: >
            Thank you for your issue!

            We haven't gotten a response to our questions above. With only the
            information that is currently in the issue, we don't have enough
            information to take action. We're going to close this but don't
            hesitate to reach out if you have or find the answers we need. If
            you answer our questions above, this issue will automatically
            reopen.
          daysUntilClose: ${{ inputs.days_until_close || 14 }}
          responseRequiredLabel: ${{ inputs.response_required_label || 'more-info-needed' }}
