name: Label incoming issues
on:
  workflow_call:
    inputs:
      triage_label:
        description: 'Label to add to new and reopened issues'
        type: string
        required: false
        default: 'triage'
      more_info_label:
        description: 'Label that indicates more info is needed'
        type: string
        required: false
        default: 'more-info-needed'
  issues:
    types:
      - reopened
      - opened
      - unlabeled

permissions:
  issues: write

jobs:
  label_incoming_issues:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ${{ inputs.triage_label || 'triage' }}
  label_more_info_issues:
    if: |
      github.event.action == 'unlabeled' && github.event.label.name == (inputs.more_info_label || 'more-info-needed')
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ${{ inputs.triage_label || 'triage' }}
